### ISSUE TITLE
Cant get this

### ISSUE THREAD

**Issue by pariharvivek92** [arslankhanali/SpotifyGeneratePlaylist#1]
Traceback (most recent call last):
File "D:\projects\SpotifyGeneratePlaylist-master\SpotifyGeneratePlaylist-master\add_songs.py", line 407, in
playlist_id_from_youtube=get_playlist_id_from_youtube(my_playlist_name,youtube)
File "D:\projects\SpotifyGeneratePlaylist-master\SpotifyGeneratePlaylist-master\add_songs.py", line 79, in get_playlist_id_from_youtube
return playlist_id
UnboundLocalError: local variable 'playlist_id' referenced before assignment

**Comment by arslankhanali** [comment]
Try adding below line on line 66 in add_songs.py:-
                   playlist_id=None
I will push the change as well.

**Comment by pariharvivek92** [comment]
bro NOT SOLVED AFTER ADDING THIS

**Comment by arslankhanali** [comment]
Getting the same error?

**Comment by pariharvivek92** [comment]
try to update your code

**Comment by pariharvivek92** [comment]
> Getting the same error?

yess can you update in your code

**Comment by arslankhanali** [comment]
I have pushed the change and reran the code for another playlist. It ran fine

**Comment by pariharvivek92** [comment]
okay I hope now this work

**Comment by arslankhanali** [comment]
You will have to get another token from Spotify, as it might have expired and I hope it runs for you now

**Comment by pariharvivek92** [comment]
> You will have to get another token from Spotify, as it might have expired and I hope it runs for you now

yeah I already get it

**Comment by pariharvivek92** [comment]
Traceback (most recent call last):
  File "D:\projects\SpotifyGeneratePlaylist-master\SpotifyGeneratePlaylist-master\add_songs.py", line 409, in <module>
    list_of_songs_from_youtube_playlist=get_list_of_songs_from_youtube_playlist(my_playlist_name,youtube,playlist_id_from_youtube)
  File "D:\projects\SpotifyGeneratePlaylist-master\SpotifyGeneratePlaylist-master\add_songs.py", line 108, in get_list_of_songs_from_youtube_playlist
    response = request.execute()
  File "C:\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\googleapiclient\http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&alt=json returned "No filter selected. Expected one of: playlistId, id, idParam">

not solved bro

**Comment by arslankhanali** [comment]
This issue seems to be from your Google API. Your usage limit has exceeded.

**Comment by arslankhanali** [comment]
Try increasing the limit or try after some time.

**Comment by pariharvivek92** [comment]
Okay
